### ISSUE TITLE
NPM error when using a specific Cordova version

### ISSUE THREAD

**Issue by adrianmarinica** [bitrise-steplib/steps-cordova-prepare#4]
```
config:
- Platform: ios,android
- Readd: false
- Version: 8.0.0
- WorkDir: <<Cordova app path>>
npm "install" "-g" "cordova" "@8.0.0"
npm ERR! code EINVALIDTAGNAME
npm ERR! Invalid tag name "@8.0.0": Tags may not have any characters that encodeURIComponent encodes.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vagrant/.npm/_logs/2018-04-11T11_51_39_209Z-debug.log
Failed to update cordova: exit status 1
```

I am getting the error message above when trying to set an explicit version for Cordova, in this case 8.0.0. Any ideas what I should do to avoid receiving that error? Thanks

**Comment by adrianmarinica** [comment]
@godrei or @kdobmayer Any ideas on a workaround for this? Or can you guys think of a fix for the issue? It's a big showstopper for me. Thanks!

**Comment by godrei** [comment]
Hi @adrianmarinica ,
sorry for my late response, Cordova prepare [v0.9.2](https://github.com/bitrise-community/steps-cordova-prepare/releases/tag/0.9.2) is released, which fixes this issue.

**Comment by adrianmarinica** [comment]
Everything works as expected. Thanks @godrei!
