### ISSUE TITLE
The platform "npm-package-arg" does not appear to be a valid cordova platform.

### ISSUE THREAD

**Issue by thibaultlavoisey** [bitrise-steplib/steps-cordova-prepare#8]
Hi everyone 👋,

I'm facing an issue using cordova-prepare@1.0.0:

<img width="1438" alt="screenshot 2018-12-31 at 14 57 38" src="https://user-images.githubusercontent.com/2022117/50561623-b2ad9600-0d0c-11e9-9fdd-574430e84b21.png">

I don't reproduce the issue locally (using Bitrise CLI) neither using the previous version of the step (0.9.2).

Any ideas how to fix it?

Thanks

**Comment by lpusok** [comment]
Please run `cordova platform rm android` and `cordova platform add android` on your machine, and push the changes to config.xml and package.json.
